backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: 'docs'
    label: 'Capitoli'
    folder: 'docs'
    create: true
    slug: '{{slug}}'
    extension: 'md'
    format: 'frontmatter'
    fields:
      - { label: 'Posizione Sidebar', name: 'sidebar_position', widget: 'number' }
      - { label: 'Titolo', name: 'title', widget: 'string' }
      - { label: 'Contenuto', name: 'body', widget: 'markdown' }
    editor:
      preview: false